export { default as About } from './About';
export { default as BookingPage } from './BookingPage';
export { default as CardDish } from './CardDish';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as HomePage } from './HomePage';
export { default as Main } from './Main';
export { default as Navbar } from './Navbar';
export { default as Testimonials } from './Testimonials';
